name: Release to Octopus

on:
  workflow_dispatch:
  push:
    branches:
    - main
    
env:
  solution: '**/*.sln'
  buildPlatform: Any CPU
  buildConfiguration: Release
  
jobs:
  OctoPetShopBuild:
    runs-on: windows-latest
    steps:
    # We take a copy of the files within the repo and put them in our working directory
    - uses: actions/checkout@v2
    # We install the latest Octopus Deploy CLI
    - uses: OctopusDeploy/install-octopus-cli-action@v1.1.8
    # We install the DotNet dependencies we need to help build the application
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish Web
      run: dotnet publish ${{ github.workspace }}\OctopusSamples.OctoPetShop.Web/OctopusSamples.OctoPetShop.Web.csproj --configuration ${{ env.BuildConfiguration }} --output ${{ github.workspace }}\output\OctoPetShop.Web\
    - name: Publish Product Service API
      run: dotnet publish ${{ github.workspace }}\OctopusSamples.OctoPetShop.ProductService/OctopusSamples.OctoPetShop.ProductService.csproj --configuration ${{ env.BuildConfiguration }} --output ${{ github.workspace }}\output\OctoPetShop.ProductService\
    - name: Publish database
      run: dotnet publish ${{ github.workspace }}\OctopusSamples.OctoPetShop.Database\OctopusSamples.OctoPetShop.Database.csproj --configuration ${{ env.BuildConfiguration }} --output ${{ github.workspace }}\output\OctoPetShop.Database\ --runtime win-x64
    - name: Publish Shopping Cart Service
      run: dotnet publish ${{ github.workspace }}\OctopusSamples.OctoPetShop.ShoppingCartService\OctopusSamples.OctoPetShop.ShoppingCartService.csproj --configuration ${{ env.BuildConfiguration }} --output ${{ github.workspace }}\output\OctoPetShop.ShoppingCartService\
